#!/bin/bash

# Viruses will be moved here when found
DUMP_DIR="${HOME}/clamav_moved"
LOG_DIR="${HOME}/logs"
LOG_FILE="clamav_scan.log"
CURRENT_LOCATION=$(pwd)

# Check for log directory & file
[ -d $LOG_DIR ] || mkdir $LOG_DIR
touch ${LOG_DIR}/${LOG_FILE} || exit

# Confirm we have something to scan
if [[ -z "$1" ]]; then
    printf "Please provide a path to scan.\n"
    exit 1
fi

# Check for dump directory, create if missing
[ -d $DUMP_DIR ] || mkdir $DUMP_DIR

# Run Scan on selected path
clamscan -r --move=${DUMP_DIR} -l ${LOG_DIR}/${LOG_FILE} $1

END_DATE=`date +%Y-%m-%d:%H:%M:%S`

echo ""
echo "Scan complete, results logged to ${LOG_DIR}/${LOG_FILE}"

# Add a bit to the log for context
echo "" >> ${LOG_DIR}/${LOG_FILE}
echo "Scan initated from: ${CURRENT_LOCATION}" >> ${LOG_DIR}/${LOG_FILE}
echo "Scan path: $1" >> ${LOG_DIR}/${LOG_FILE}
echo "Scan completed at: ${END_DATE}" >> ${LOG_DIR}/${LOG_FILE}
