#!/bin/bash

# Viruses will be moved here when found
DUMP_DIR="${HOME}/VIRUS"
LOG_DIR="${HOME}/logs"
LOG_FILE="clamav_scan.log"

# Check for log directory & file
[ -d $LOG_DIR ] || mkdir $LOG_DIR
touch ${LOG_DIR}/${LOG_FILE} || exit

# Confirm we have something to scan
if [[ -z "$1" ]]; then
    printf "Please provide a path to scan.\n"
    exit 1
fi

# Check for dump directory, create if missing
[ -d $DUMP_DIR ] || mkdir $DUMP_DIR

# Update definitions
freshclam

# Run Scan on selected path
clamscan -r --move=${DUMP_DIR} -l ${LOG_DIR}/${LOG_FILE} $1


