##############################################
# brew bundle --file=~/.dots/dots/homebrew/Brewfile
##############################################

# Taps
tap "caskroom/cask"
tap "homebrew/apache"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/dupes"
tap "homebrew/php"
tap "homebrew/science"
tap "homebrew/services"
tap "homebrew/versions"


# Build tools
brew "cmake"

# Git
brew "hub"
brew "hubflow"
brew "git"
brew "git-flow"

# Libraries
brew "msgpack"
brew "libxml2"
brew "libyaml"
brew "openssl"


# Languages
# brew "php56"
# brew "php70"
brew "python"
brew "node"


# Tools
brew "vim"
brew "wget"
brew "tidy-html5"
brew "redis"
brew "homebrew/apache/httpd24"


# General Apps
cask "slack"
cask "google-chrome"
cask "google-drive"
cask "1password"
cask "dropbox"
cask "iterm2"
cask "sketch"
cask "github-desktop"
cask "macdown"


# Utilities
brew "cmatrix"
brew "coreutils"
brew "p7zip"
brew "ruby-build"
brew "rbenv"
