set nocompatible

" Syntax Highlighting
syntax on

" Show Edit Mode on Last Line
set showmode

" Display line numbers on the left
set number

" Hilight Search Strings
set hlsearch

" Use case insensitive search, except when using capital letters
set ignorecase
set smartcase

" Better command-line completion
set wildmenu

" Show partial commands in the last line of the screen
set showcmd

" Display the cursor position on the last line of the screen or in the status line of a window
set ruler

" Instead of failing a command because of unsaved changes, instead ask if you wish to save changed files.
set confirm

" Use visual bell instead of beeping when doing something wrong
set visualbell
